[build]
  publish = ".output/public"
  command = "npm run generate"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200